# Generated by Django 5.0.4 on 2024-04-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kosar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoftheproduct', models.CharField(max_length=255)),
                ('pice', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('shopping_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
