# Generated by Django 5.0.4 on 2024-04-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_profiledatas'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledatas',
            name='keresztnev',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiledatas',
            name='lakcim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiledatas',
            name='vezeteknev',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profiledatas',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
